---

- name: recover JAVA_HOME
  shell: "set -o pipefail && (java -XshowSettings 2>&1; true) |awk '/java.home/ { print $3 }'"
  args:
    executable: /bin/bash
  changed_when: false
  register: javasettings
- debug: var=javasettings.stdout

- name: set java_home
  set_fact:
    java_home: "{{ javasettings.stdout | default('') }}"
