---
# tasks file for jira (Ubuntu specific)

- name: Trusty | python SNI dependencies
  apt:
    name:
      - python-urllib3
      - python-openssl
      - python-pyasn1
    state: present
  when: ansible_distribution_release == 'trusty'

- name: Trusty | python pip SNI dependencies
  pip:
    name: ndg-httpsclient
    state: present
  when: ansible_distribution_release == 'trusty'

- name: Ensure network tools are present (serverspec testing)
  package:
    name: iproute2
    state: present
  when: jira_testing
